{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rosm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rosm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rosm/rosm_{{ version }}.tar.gz
  sha256: c3c1443af1206ec0d476740f34ea09ecac581599aa6b7377cc0362d088294e08

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-curl
    - r-glue
    - r-jpeg
    - r-png
    - r-progress
    - r-rlang
    - r-wk
  run:
    - r-base
    - r-curl
    - r-glue
    - r-jpeg
    - r-png
    - r-progress
    - r-rlang
    - r-wk

test:
  commands:
    - $R -e "library('rosm')"           # [not win]
    - "\"%R%\" -e \"library('rosm')\""  # [win]

about:
  home: https://github.com/paleolimbot/rosm
  license: GPL-2.0-only
  summary: Download and plot Open Street Map <http://www.openstreetmap.org/>, Bing Maps <http://www.bing.com/maps> and other tiled map sources. Use to create  basemaps quickly and add hillshade to vector-based maps.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: rosm
# Type: Package
# Title: Plot Raster Map Tiles from Open Street Map and Other Sources
# Version: 0.2.4
# Encoding: UTF-8
# Authors@R: c(person("Dewey", "Dunnington", role = c("aut", "cre"), email = "dewey@fishandwhistle.net", comment = c(ORCID = "0000-0002-9415-4582")), person("Timothee", "Giraud", role = "ctb"))
# Maintainer: Dewey Dunnington <dewey@fishandwhistle.net>
# Description: Download and plot Open Street Map <http://www.openstreetmap.org/>, Bing Maps <http://www.bing.com/maps> and other tiled map sources. Use to create  basemaps quickly and add hillshade to vector-based maps.
# License: GPL-2
# LazyData: TRUE
# Imports: curl, abind, jpeg, png, sp, rgdal, rjson, methods, plyr, prettymapr, tools
# Suggests: cartography, raster, testthat, covr, withr, knitr, rmarkdown
# URL: https://github.com/paleolimbot/rosm
# BugReports: https://github.com/paleolimbot/rosm/issues
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-03-15 16:46:52 UTC; dewey
# Author: Dewey Dunnington [aut, cre] (<https://orcid.org/0000-0002-9415-4582>), Timothee Giraud [ctb]
# Repository: CRAN
# Date/Publication: 2019-03-15 17:10:33 UTC
