appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: k/4W1MuoUOdXUCfnymTIFDBJOkNDMBjISPaCDPklALwSpFqzyr/UnXvy1VoFHnNrAXS/aqZgeU1FrSoq3HfShqnLHXqyjHdl+iAaOEOG2Siud15qGalZsPjdbKzYj6AUzJDGtUWCzZjhf9A01yxs14keisi5on5EaEPAm0G252J28qujgOGSGip6JxRtqfmiQCuEgs1zN1/tkE+Fghg74uhr0qOXgNR+Q4iIQYQymGeZ9UzRoDAIOuI4ohV8/1qsNqGpmNVK5R35mHJoqdyJ0b+DDLcW7xb4lD7uksXG4dJqlXdl9chnQK10i62VzzFxJQIxJYTV/d4P1nTLeuBJfuUT/77MAQYgMSIcFCDT7KwL225zWSKztzGSieIvZssf6MWnRsun2T8Zg0yI4UpqgrUtDQ0omOhMX0Jjc0xgaK8wB/Llpr2nChPp5Y8uoOTEi2Hin2fwBDYu1fBVsAMGeN3ZD3XDByZCra1rPmcP2CaKZ53ERwwSlS9oMmrjN3H63z6OQ2tTwdqy7cqkWOusrMAhx28Bg4PAM4xZ6XVBlgTxrz7b+g7xZZoEeHSRDUYEv0EJPvX39taQstI9EeWqDU8vbgENQkgzP3UIVe7JHngQgArWcCKDzwWysjqwE1AQA/jyimrRX6B/0a7vDkc/1ayYx+LTo08frjzNIzZOy8w=
conda_forge_output_validation: true
